DROP TABLE IF EXISTS films CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS film_genres;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS user_friends;
DROP TABLE IF EXISTS user_film_lake;
DROP TABLE IF EXISTS mpa;

CREATE TABLE if not exists users (
  user_id integer generated by default as identity not null PRIMARY KEY,
  name varchar,
  login varchar not null,
  email varchar not null unique,
  birthday date
);

CREATE TABLE if not exists mpa (
  mpa_id integer generated by default as identity not null PRIMARY KEY,
  mpa_name varchar
);

CREATE TABLE if not exists films (
  film_id integer generated by default as identity not null PRIMARY KEY,
  name varchar not null,
  description varchar(200),
  release_date date,
  duration integer,
  rate integer,
  mpa_id integer REFERENCES mpa (mpa_id) on delete cascade
);

CREATE TABLE if not exists user_film_like (
  user_id integer REFERENCES users (user_id) on delete cascade,
  film_id integer REFERENCES films (film_id) on delete cascade,
  PRIMARY KEY (user_id, film_id)
);

CREATE TABLE if not exists user_friends (
  user_id integer,
  friend_id integer,
  confirmed boolean
);

CREATE TABLE if not exists genres (
  genre_id integer generated by default as identity not null PRIMARY KEY,
  genre_name varchar not null unique
);

CREATE TABLE if not exists film_genres (
  film_id integer REFERENCES films (film_id) on delete cascade,
  genre_id integer REFERENCES genres (genre_id) on delete cascade,
  PRIMARY KEY (film_id, genre_id)
);