CREATE TABLE "users" (
  "user_id" integer generated by default as identity not null PRIMARY KEY,
  "name" varchar,
  "login" varchar not null,
  "email" varchar not null unique,
  "birthday" date
);

CREATE TABLE "films" (
  "film_id" integer generated by default as identity not null PRIMARY KEY,
  "name" varchar not null,
  "description" varchar(200),
  "release_date" date,
  "duration" integer
);

CREATE TABLE "user_film_like" (
  "user_id" integer REFERENCES "users" ("user_id") on delete cascade,
  "film_id" integer REFERENCES "films" ("film_id") on delete cascade,
  PRIMARY KEY ("user_id", "film_id")
);


CREATE TABLE "user_friends" (
  "user_id" integer,
  "friend_id" integer
);

CREATE TABLE "genres" (
  "genre_id" integer generated by default as identity not null PRIMARY KEY,
  "name" varchar not null unique
);

CREATE TABLE "film_genres" (
  "film_id" integer REFERENCES "films" ("film_id") on delete cascade,
  "genre_id" integer REFERENCES "genres" ("genre_id") on delete cascade,
  PRIMARY KEY ("film_id", "genre_id")
);